durvani/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('quizz.urls',namespace="quizz")),  
    path('durvani/', include('blog.urls',namespace="blog")),  

    path('auth/', include('authentication.urls',namespace='account')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL,document_root='static/static_cdn/build/'+settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
# urlpatterns += [re_path(r'^.*\/', TemplateView.as_view(template_name='base.html'))] 

admin.site.index_title="ContentBond"
admin.site.site_header="The ContentBond Administration"
admin.site.site_title="ContentBond"

quizz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView,RedirectView

app_name='quizz'
urlpatterns = [
    path('getcsrf/default/',views.get_csrf,name="csrf"),
    path('quiz/',views.quiz,name="quiz"),
    path('profile/',views.profile),
    path('ex1_templateview/',TemplateView.as_view(template_name="1templateview.html",extra_context={'title':'extracontext'})),
    path('ex2_templateview/',views.Ex2View.as_view()),
    path('rdt/', RedirectView.as_view(url='http://youtube.com/veryacademy'), name='go-to-very'),
    path('ex3/<int:pk>/',views.PostPreLoadTaskView.as_view(),name='redirect-task'),
    path('ex4/<int:pk>/',views.SinglePostView.as_view(),name='singlepost'),
    path('listviewex/',views.BookListView.as_view(),name='book-list'),
    path('<slug:slug>/',views.BookDetailView.as_view(),name='book-detail'),
    path('g/<str:genre>/',views.BookListView.as_view(),name='book-detailkwarg'),
    path('g/add/form/', views.AddBookView.as_view(), name='add'),
    path('g/addcreate/form/', views.AddBookViewcreate.as_view(), name='addcreate'),
    path('g/addupdate/form/<slug:pk>', views.AddEditView.as_view(), name='addupdate'),

    path('auth/signin',views.movieplex),
    path('auth/password_reset/',views.movieplex2),
    path('admin/contentrequest/',views.movieplex),

    path('admin/saveproduct/',views.save_product,name='saveproduct'),
    path('admin/saveproductbyadmin/',views.save_product_by_admin,name='saveproductadmin'),
    path('admin/editproductsave/',views.editProductSave,name='editproductsave'),

    path('admin/getadminmesssages/',views.GetAdminMessages,name='getadminmessages'),
    path('admin/getadminmesssagesreply/',views.GetAdminMessagesReply,name='getadminmessagesreply'),
    path('admin/deletemessages/',views.DeleteMessages,name='deletemessages'),

    
    
    path('admin/requestsaveproduct/',views.requestsaveproduct,name='requestsaveproduct'),
    path('admin/getProductsall/',views.getProductsall,name='getProductsall'),
    path('admin/getproductsofcreator/',views.getProductsofcreator,name='getProductsofcreator'),
    path('admin/getproductsallbyusers/',views.getProductsallbyUsers,name='getProductsallbyUsers'),
    path('admin/getgroupproductsallbyusers/',views.getgroupProductsallbyUsers,name='getgroupProductsallbyUsers'),
    

    path('admin/getproductbyid/',views.getProductById,name='getProductById'),


    
    # Group
    path('admin/creategroup/',views.createGroup,name='createGroup'),
    path('admin/getallgroups/',views.getAllgroups,name='getAllgroups'),
    path('admin/deletegroups/',views.deleteGroups,name='deleteGroups'),


    

    path('admin/assignedtogroup/',views.assignedtogroup,name='assignedtogroup'),


    path('admin/getproductchip/', views.getProductChip, name='getProductChip'),
    path('admin/saveproductsforusers/', views.UserProductSave, name='UserProductSave'),
    path('admin/saveproductsforgroups/', views.GroupProductSave, name='GroupProductSave'),

    # path('admin/getallprodlikes/',views.getProductswithlikes,name='getProductswithlikes'),
    path('admin/addliketoproduct/',views.addliketoproduct,name='addliketoproduct'),
    path('admin/addboughtproduct/',views.addboughtproduct,name='addboughtproduct'),
    path('admin/getproductsallbagged/',views.getProductsallbagged,name='getProductsallbagged'),
    path('admin/getproductsallliked/',views.getProductsallliked,name='getProductsallliked'),
    path('admin/productstatus/',views.productstatus,name='productstatus'),
    path('admin/deleteproduct/',views.deleteproduct,name='deleteproduct'),


    

    # Admin Copy paths
    path('admin/getproductsalllikedbyid/',views.getProductsalllikedbyuserid,name='getProductsalllikedbyuserid'),
    path('admin/getproductsallbaggedbyid/',views.getProductsallbaggedbyuserid,name='getProductsallbaggedbyuserid'),
    path('admin/getproductsallbyusersbyid/',views.getProductsallbyUsersbyid,name='getProductsallbyUsersbyid'),
    path('admin/getuploadsallbyusersbyid/',views.getUploadsallbyusersbyid,name='getUploadsallbyusersbyid'),
    


    # Chat

    path('admin/chat/users/',views.MessageChatusers,name='messageChatusers'),
    path('admin/chat/savemessage/',views.MessageChatMessages,name='savemessage'),

    path('admin/getsellermessages/',views.getsellermessages,name='getsellermessages'),
    path('admin/getbuyermessages/',views.getbuyermessages,name='getbuyermessages'),
    path('admin/getallgroupsmessages/',views.GetgroupMessages,name='getallgroupsmessages'),

    path('admin/getnotifications/',views.NotifyGetter,name='NotifyGetter'),


    # Dashboard

    path('admin/dashboardview/',views.dashboardView,name='dashboardview'),
    path('admin/dashboardviewseller/',views.dashboardviewsellerView,name='dashboardviewseller'),
    path('admin/dashboardviewbuyerview/',views.dashboardviewbuyerView,name='dashboardviewbuyerView'),

    path('admin/testpurpose/',views.testpurpose,name='testpurpose')
    
]

urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizz.urls',namespace="quizz")),  

    path('auth/', include('authentication.urls',namespace='account')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL,document_root='static/static_cdn/build/'+settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='base.html'))] 

admin.site.index_title="ContentBond"
admin.site.site_header="The ContentBond Administration"
admin.site.site_title="ContentBond"

quizz/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.middleware.csrf import get_token
from quizz.models import Profile,Books,Content,ProductGroup,Likedproducts,Boughtedproducts,AssignedUsersGroup,ProductAssigns,MessageInbox,ContentSaveNotifyer,MessageChatter,MessageRequest,ProductRequest,Contentcategorynumbertoname
from django.contrib.auth.models import User, Group, Permission
from django.views.generic.base import TemplateView,RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView,CreateView,UpdateView
from django.db.models import F
from django.utils import timezone
from django.core.paginator import Paginator
from .forms import AddForm,ProductForm,ProductRequestForm,GroupForm,MessageInboxForm,MessageChatterForm
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_protect,csrf_exempt
import json
from authentication.utils import DatabaseDynamic
from .serializers import ProductsSerializer,ProductAssignsSerializer,ProductGroupSerializer,MessageInboxSerializer,MessageChatterSerializer,ContentSaveNotifyerSerializer,ProductRequestSerializer,LikedproductsSerializer,BoughtedproductsSerializer
from authentication.serializers import CustomUserSerializer
import uuid
import math
from rest_framework.decorators import api_view, schema,permission_classes
from rest_framework.permissions import IsAuthenticated,AllowAny
from rest_framework.response import Response
from rest_framework.pagination import PageNumberPagination

import datetime
from dateutil.relativedelta import relativedelta

from .utils import Util,MassMail

def get_random_code():
    code = str(uuid.uuid4())[:8].replace('-', '').lower()   
    return code
@ensure_csrf_cookie
def get_csrf(request):
    response = JsonResponse({"Info": "Success - Set CSRF cookie"})
    response["X-CSRFToken"] = get_token(request)
    return response


def quiz(request):
    return render(request,'index.html')
    
    
def profile(request):
    data = Profile.objects.all()
    for i in data:
        print(i.user_ptr.is_active)
    context = {
        'data':'i.content'
    }
    # return JsonResponse(context)
    return render(request,'index.html')

@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
def dashboardView(request):
    sellers = 0
    buyers=0
    enquiries=0
    leads=0
    error=""
    likedcount = 0
    interestcount =0
    messagecount=0
    usersarray =[]
    contentarray=[]
    weekdays = []


    try:
        if request.user.is_superuser:
            sellers = Profile.objects.filter(content="creator").count()    
            buyers = Profile.objects.filter(content="producer").count()  
            sellerenquiries = MessageChatter.objects.filter(sendertype="creator").count()
            buyerenquiries = MessageChatter.objects.filter(sendertype="producer").count()

            monthsnamearray = ['','Jan','Feb','Mar','April','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

            for dates in range(1,7):
                # usercount = 0
                # productcount=0
                weekdaysexplorer = datetime.datetime.today() - relativedelta(days=int(dates))
                usercount = User.objects.filter(date_joined = datetime.datetime(weekdaysexplorer.year, weekdaysexplorer.month, weekdaysexplorer.day)).count()
                usersarray.append(int(usercount))

                productcount = Content.objects.filter(created = datetime.date(weekdaysexplorer.year, weekdaysexplorer.month, weekdaysexplorer.day)).count()
                contentarray.append(int(productcount))

                weekdays.append((str(weekdaysexplorer.day) + str(monthsnamearray[weekdaysexplorer.month])))
        else:
            sellerenquiries = MessageChatter.objects.filter(sender=request.user.id).count()
            likedcount = Likedproducts.objects.filter(user=request.user.id).count()
            interestcount = Boughtedproducts.objects.filter(user=request.user.id).count()
            
        
        
        

            
            
 
    except Exception as e:
        error = str(e)

    context = {
        'sellers':sellers,
        'buyers':buyers,
        'sellerenquiries':sellerenquiries,
        'buyerenquiries':buyerenquiries,
        'likedcount':likedcount,
        'interestcount':interestcount,
        'usersarray':usersarray,
        'contentarray':contentarray,
        'weekdays':weekdays,
        'messagecount':messagecount,
        'error':error
        


    }
    # return JsonResponse(context)
    return Response(context)



@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
def dashboardviewsellerView(request):
    sellers = 0
    buyers=0
    enquiries=0
    leads=0
    error=""
    likedcount = 0
    interestcount =0


    try:
        
        # sellers = Profile.objects.filter(content="creator").count()    
        # buyers = Profile.objects.filter(content="producer").count()  
        totaluploads = Content.objects.filter(author = request.user.id).count()
        sellerenquiries = MessageChatter.objects.filter(sendertype="creator").count()
        likedcount = Likedproducts.objects.filter(user=request.user.id).count()
        interestcount = Boughtedproducts.objects.filter(user=request.user.id).count()
        
    
    except Exception as e:
        error = str(e)

    context = {
        'totaluploads':totaluploads,
        'sellerenquiries':sellerenquiries,        
        'likedcount':likedcount,
        'interestcount':interestcount,
        'error':error


    }
    # return JsonResponse(context)
    return Response(context)


@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])

def dashboardviewbuyerView(request):
    sellers = 0
    buyers=0
    enquiries=0
    leads=0
    error=""
    likedcount = 0
    interestcount =0


    try:
        
        # sellers = Profile.objects.filter(content="creator").count()    
        # buyers = Profile.objects.filter(content="producer").count()  
        # totaluploads = Content.objects.filter(author = request.user.id).count()
        buyerenquiries = MessageChatter.objects.filter(sendertype="producer").count()
        likedcount = Likedproducts.objects.filter(user=request.user).count()
        interestcount = Boughtedproducts.objects.filter(user=request.user).count()
        
    
    except Exception as e:
        error = str(e)

    context = {
        # 'totaluploads':totaluploads,
        'sellerenquiries':buyerenquiries,        
        'likedcount':likedcount,
        'interestcount':interestcount,
        'error':error


    }
    # return JsonResponse(context)
    return Response(context)




class Ex2View(TemplateView):
    template_name = "1templateview.html"
    # template_engine = ""
    # get_context_data(**kwargs) is method inherited from ContextMixin

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['data'] = Books.objects.all()
        # context['title'] = str(*args['id'])
        print('imhere')
        print(self.request.GET.get('id'))  ##### Working Here
        return context

class SinglePostView(RedirectView):
    url="http://youtube.com/pyplane"
            
class PostPreLoadTaskView(RedirectView):

    # url="http://youtube.com/veryacademy"

    # OR
    
    pattern_name ='quizz:singlepost'

    # Permanent = Http status code returned

    def get_redirect_url(self, *args, **kwargs):
        # Updating page count of a page visited
        # get_object_or_404(post,pk=kwargs['pk'])
        # .save()

        #  OR

        # filter,update
        
        # count = F('count') + 1
        count =0
        print(count)

        return super().get_redirect_url(*args, **kwargs)
# DetailView nosupports pagination, noform,no return update delete
class BookDetailView(DetailView):
    model = Books
    # upto now is enough if placed templatefile here quizz/books_detail.html

    # overriting
    template_name = 'book-detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = Books.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count')+1)
        context['time'] = timezone.now()
        return context
        # refer django singleobjectmixin for this view


# listview supports pagination, but noform,no return update delete

class BookListView(ListView):
    model = Books
    template_name = "home.html"
    context_object_name = "books"
    paginate_by = 2
    # upto here is enough
    # queryset = Books.objects.all()[:2]

    def get_queryset(self, *args, **kwargs):
        # return Books.objects.all()[:2]
        return Books.objects.filter(genre__icontains=self.kwargs.get('genre'))
# Multipleobjectmixin

# Formview not displaying a form page, saving data to a database

class AddBookView(FormView):
    template_name = 'add.html'
    form_class = AddForm
    success_url = '/g/add/form/'
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
# formmixin

# Createview dont supplort forms

class AddBookViewcreate(CreateView):
    model = Books
    form_class = AddForm
    # we can use initial

    # fields = ['title']

    template_name = 'add.html'
    success_url = '/g/add/form/'
    # the below get_initial is optional 
    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['title'] = 'Enter Title'
        return initial
# form saves automatically without extracode
class AddEditView(UpdateView):
    model = Books
    form_class = AddForm
    template_name = 'add.html'
    success_url = '/books/'
# in update view get_object rertrieves the data
# in createview get_object = None
@ensure_csrf_cookie
def movieplex(request):
    return render(request,'index.html')


def movieplex2(request):

quizz/templates/1templateview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ex1 Template View</title>
</head>
<body>
    {{title}}<br>
    {{data}}
</body>
</html>

quizz/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form view</title>
</head>
<body>
formview
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</body>
</html>

quizz/templates/book-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Detail view</title>
</head>
<body>
    {% comment %} {{object.title}}<br> {% endcomment %}
    {{book.title}}<br>
    {{book.isbn}}<br>
    {{time}}
    
</body>
</html>

quizz/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ListView</title>
</head>
<body>
    {% for book in books %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'quizz:book-detail' slug=book.slug %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{book.genre}}</small>
                                    <small class="text-muted">{{book.isbn}}</small>
                                </div>
                                <small class="text-muted">{{time}}</small>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
</body>
</html>

quizz/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="/logo192.png" />
    <link rel="manifest" href="/manifest.json" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap"
      rel="stylesheet"
    />
    <title>React App</title>
    <style>
      ::-webkit-scrollbar {
        width: 6px;
      }
      ::-webkit-scrollbar-track {
        box-shadow: inset 0 0 2px #7773732e;
        border-radius: 3px;
      }
      ::-webkit-scrollbar-thumb {
        background: #7773732e;
        border-radius: 3px;
      }
      ::-webkit-scrollbar-thumb:hover {
        background: #034078;
      }
    </style>
    <link href="/static/css/main.df0b1890.chunk.css" rel="stylesheet" />
  </head>
  <body>
  {% csrf_token %}
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
    <script type="application/javascript"></script>
    <script>
      !(function (e) {
        function t(t) {
          for (
            var n, a, i = t[0], c = t[1], l = t[2], s = 0, p = [];
            s < i.length;
            s++
          )
            (a = i[s]),
              Object.prototype.hasOwnProperty.call(o, a) &&
                o[a] &&
                p.push(o[a][0]),
              (o[a] = 0);
          for (n in c)
            Object.prototype.hasOwnProperty.call(c, n) && (e[n] = c[n]);
          for (f && f(t); p.length; ) p.shift()();
          return u.push.apply(u, l || []), r();
        }
        function r() {
          for (var e, t = 0; t < u.length; t++) {
            for (var r = u[t], n = !0, i = 1; i < r.length; i++) {
              var c = r[i];
              0 !== o[c] && (n = !1);
            }
            n && (u.splice(t--, 1), (e = a((a.s = r[0]))));
          }
          return e;
        }
        var n = {},
          o = { 1: 0 },
          u = [];
        function a(t) {
          if (n[t]) return n[t].exports;
          var r = (n[t] = { i: t, l: !1, exports: {} });
          return e[t].call(r.exports, r, r.exports, a), (r.l = !0), r.exports;
        }
        (a.e = function (e) {
          var t = [],
            r = o[e];
          if (0 !== r)
            if (r) t.push(r[2]);
            else {
              var n = new Promise(function (t, n) {
                r = o[e] = [t, n];
              });
              t.push((r[2] = n));
              var u,
                i = document.createElement("script");
              (i.charset = "utf-8"),
                (i.timeout = 120),
                a.nc && i.setAttribute("nonce", a.nc),
                (i.src = (function (e) {
                  return (
                    a.p +
                    "static/js/" +
                    ({}[e] || e) +
                    "." +
                    { 3: "4fa57dee" }[e] +
                    ".chunk.js"
                  );
                })(e));
              var c = new Error();
              u = function (t) {
                (i.onerror = i.onload = null), clearTimeout(l);
                var r = o[e];
                if (0 !== r) {
                  if (r) {
                    var n = t && ("load" === t.type ? "missing" : t.type),
                      u = t && t.target && t.target.src;
                    (c.message =
                      "Loading chunk " +
                      e +
                      " failed.\n(" +
                      n +
                      ": " +
                      u +
                      ")"),
                      (c.name = "ChunkLoadError"),
                      (c.type = n),
                      (c.request = u),
                      r[1](c);
                  }
                  o[e] = void 0;
                }
              };
              var l = setTimeout(function () {
                u({ type: "timeout", target: i });
              }, 12e4);
              (i.onerror = i.onload = u), document.head.appendChild(i);
            }
          return Promise.all(t);
        }),
          (a.m = e),
          (a.c = n),
          (a.d = function (e, t, r) {
            a.o(e, t) ||
              Object.defineProperty(e, t, { enumerable: !0, get: r });
          }),
          (a.r = function (e) {
            "undefined" != typeof Symbol &&
              Symbol.toStringTag &&
              Object.defineProperty(e, Symbol.toStringTag, { value: "Module" }),
              Object.defineProperty(e, "__esModule", { value: !0 });
          }),
          (a.t = function (e, t) {
            if ((1 & t && (e = a(e)), 8 & t)) return e;
            if (4 & t && "object" == typeof e && e && e.__esModule) return e;
            var r = Object.create(null);
            if (
              (a.r(r),
              Object.defineProperty(r, "default", { enumerable: !0, value: e }),
              2 & t && "string" != typeof e)
            )
              for (var n in e)
                a.d(
                  r,
                  n,
                  function (t) {
                    return e[t];
                  }.bind(null, n)
                );
            return r;
          }),
          (a.n = function (e) {
            var t =
              e && e.__esModule
                ? function () {
                    return e.default;
                  }
                : function () {
                    return e;
                  };
            return a.d(t, "a", t), t;
          }),
          (a.o = function (e, t) {
            return Object.prototype.hasOwnProperty.call(e, t);
          }),
          (a.p = "/"),
          (a.oe = function (e) {
            throw (console.error(e), e);
          });
        var i = (this.webpackJsonpstatic_cdn =
            this.webpackJsonpstatic_cdn || []),
          c = i.push.bind(i);
        (i.push = t), (i = i.slice());
        for (var l = 0; l < i.length; l++) t(i[l]);
        var f = c;
        r();
      })([]);
    </script>
    <script src="/static/js/2.4da9ed4e.chunk.js"></script>
    <script src="/static/js/main.3728a2a4.chunk.js"></script>
  </body>
</html>

quizz/templates/offline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Offline html</title>
</head>
<body>
    <div>
        Offline Document
    </div>
</body>
</html>